import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("index_1.csv")

# Top 10 Rows 
print(data.head(10))

# Information about dataset
print(data.info())

#describe the dataset 
print(data.describe())

print("------------------Data Cleaning--------------------")

# checking for null values
print(data.isnull().sum())

# See the rows with null values
print(data[data["card"].isnull()])

# Fill the values 
data["card"] = data["card"].fillna("Paypal")
print(data)

# Drop Duplicates values 
data = data.drop_duplicates()
print(data)

# apply 

def classify_money (money):
    if money>=30 :
        return "High"
    else : 
        return "Low"

data["money_category"] = data["money"].apply(classify_money)
print(data)

print("--------------Data Visualization---------------")
# Hghest sales of coffee

name = data["coffee_name"].value_counts()
print(name)
plt.bar(name.index, name.values)

plt.xlabel("Coffee_name")
plt.ylabel("Numbers of Orders")
plt.title("Most Popular Coffee")

plt.show()

# Revenue group by coffee name 
revenue = data.groupby('coffee_name')["money"].sum().sort_values(ascending= False)
print(revenue)

plt.bar(revenue.index, revenue.values)
plt.xlabel("Coffee Name")
plt.ylabel("Total Revenue")
plt.title("Revenue Generated by Each Coffee")
plt.show()